import { describe, expect, it } from 'vitest';
import {
  alu, commitCycle, createState, decode, encode, factorialSource, parseAssembly,
  readRegister, traceCycle, writeRegister,
} from '../src/engine';

// Encodings below are fixed reference words, calculated from the published
// RISC-V field layout rather than generated by the engine under test.
const ADDI_T0_ZERO_3 = 0x00300293;
const ADDI_T1_ZERO_0 = 0x00000313;
// imm=4094 has imm[10:5]=63, imm[4:1]=15, and imm[11]=1; bit 12 is zero.
const BEQ_X1_X2_PLUS_4094 = 0x7e208fe3;
const BEQ_X1_X2_MINUS_4096 = 0x80208063;

describe('independent RISC-V reference encodings', () => {
  it('matches the canonical addi word and decodes register aliases', () => {
    expect(encode({ name: 'addi', rd: 5, rs1: 0, imm: 3 })).toBe(ADDI_T0_ZERO_3);
    expect(decode(ADDI_T0_ZERO_3)).toMatchObject({ name: 'addi', rd: 5, rs1: 0, imm: 3, a1: 0, a3: 5 });
    expect(decode(ADDI_T1_ZERO_0)).toMatchObject({ name: 'addi', rd: 6, rs1: 0, imm: 0 });
  });

  it('reconstructs signed extreme B immediates from their scattered fields', () => {
    expect(encode({ name: 'beq', rs1: 1, rs2: 2, imm: 4094 })).toBe(BEQ_X1_X2_PLUS_4094);
    expect(encode({ name: 'beq', rs1: 1, rs2: 2, imm: -4096 })).toBe(BEQ_X1_X2_MINUS_4096);
    expect(decode(BEQ_X1_X2_PLUS_4094)).toMatchObject({ name: 'beq', rs1: 1, rs2: 2, imm: 4094 });
    expect(decode(BEQ_X1_X2_MINUS_4096)).toMatchObject({ name: 'beq', rs1: 1, rs2: 2, imm: -4096 });
  });

  it('rejects unsupported funct3 and funct7 encodings instead of guessing', () => {
    const addWithBadFunct3 = (ADDI_T0_ZERO_3 & 0x7f) | (0b001 << 12) | (0b0110011 << 0) | (5 << 7) | (1 << 20);
    const addWithBadFunct7 = 0x02000033; // R-type SUB-shaped word with funct3=000; unsupported funct7 must not decode as ADD.
    expect(() => decode(addWithBadFunct3)).toThrow();
    expect(() => decode(addWithBadFunct7)).toThrow();
  });

  it('keeps physical register aliases within the low-three-bit lab file', () => {
    // Standard fields can name x13/x15; the lab datapath wires only address[2:0].
    const word = 0x00f68533; // add x10,x13,x15
    const decoded = decode(word, 'lab');
    expect(decoded).toMatchObject({ name: 'add', a1: 5, a2: 7, a3: 2 });
    expect(() => parseAssembly('add a0, a3, a7', 'lab')).toThrow();
    expect(readRegister([0, 11, 22, 33, 44, 55, 66, 77], 13)).toBe(55);
  });
});

describe('ALU and cycle boundary reference behavior', () => {
  it('wraps arithmetic to 32 bits and performs signed SLT at both extremes', () => {
    expect(alu(0xffffffff, 1, '000')).toMatchObject({ y: 0, zero: 1 });
    expect(alu(0x7fffffff, 1, '000').y).toBe(0x80000000);
    expect(alu(0x80000000, 0x7fffffff, '101').y).toBe(1);
    expect(alu(0x7fffffff, 0x80000000, '101').y).toBe(0);
  });

  it('selects taken and untaken beq targets and wraps the 8-bit lab PC', () => {
    const state = createState('lab');
    state.pc = 252;
    state.registers[1] = 7;
    const taken = traceCycle(state, encode({ name: 'beq', rs1: 1, rs2: 1, imm: 4 }));
    expect(taken).toMatchObject({ pc: 252, pcPlus4: 0, branchTaken: true, branchTarget: 0, pcNext: 0 });
    expect(state.pc).toBe(252); // tracing has no side effects
    state.registers[2] = 8;
    const untaken = traceCycle(state, encode({ name: 'beq', rs1: 1, rs2: 2, imm: -4 }));
    expect(untaken).toMatchObject({ branchTaken: false, pcNext: 0 });
  });

  it('keeps writes at commit time and rejects a stale trace', () => {
    const state = createState('lab');
    const trace = traceCycle(state, ADDI_T0_ZERO_3);
    expect(state.registers[5]).toBe(0);
    const next = commitCycle(state, trace);
    expect(next.registers[5]).toBe(3);
    expect(state.registers[5]).toBe(0);
    expect(() => commitCycle(next, trace)).toThrow();
  });

  it('keeps x0 hardwired through writes', () => {
    const registers = writeRegister([0, 1, 2, 3, 4, 5, 6, 7], 0, 99, true);
    expect(registers[0]).toBe(0);
    expect(readRegister(registers, 0)).toBe(0);
  });
});

describe('factorial source contract', () => {
  it.each([0, 3, 8])('starts with the substituted input and ends in a self branch for n=%i', (n) => {
    const source = factorialSource(n);
    const lines = parseAssembly(source, 'lab');
    expect(lines[0].word).toBe(encode({ name: 'addi', rd: 5, rs1: 0, imm: n }));
    expect(lines[0].word).toBe((ADDI_T0_ZERO_3 & 0xfffff) | (n << 20));
    expect(lines.at(-1)?.instruction.name).toBe('beq');
    expect(lines.at(-1)?.instruction.rs1).toBe(lines.at(-1)?.instruction.rs2);
    expect(lines.at(-1)?.instruction.imm).toBe(0);
  });
});
